# config.yml
backend:
  backend:
 name: git-gateway
 branch: main
 
local_backend: true

publish_mode: editorial_workflow

logo_url: docs/assets/images/brand-logo-dark.svg

media_folder: 'assets/images/' # Media files will be stored in the repo under public/
public_folder: '/assets/images/' # The src attribute for uploaded media will begin with /

collections:
  - name: 'Test for CMS' # Used in routes, e.g., /admin/collections/docs
    label: 'Test for CMS' # Used in the UI
    folder: 'docs/stories/Test for CMS/' # The path to the folder where the mdx documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}.stories' # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: [ '<!--', '-->' ]
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    editor:
      preview: true

  - name: 'Getting Started' # Used in routes, e.g., /admin/collections/docs
    label: 'Getting Started' # Used in the UI
    folder: 'docs/stories/gettingStarted/' # The path to the folder where the mdx documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}.stories' # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: ['<!--', '-->']
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Body', name: 'body', widget: 'markdown'}
    editor:
      preview: true

  - name: 'Component' # Used in routes, e.g., /admin/collections/docs
    label: 'Component Docs' # Used in the UI
    folder: 'docs/stories/components/' # The path to the folder where the mdx documents are stored
    create: true # Allow users to create new documents in this collection
    extension: mdx
    slug: '{{title}}.stories' # Filename template, e.g., title.stories.mdx
    format: yaml-frontmatter
    frontmatter_delimiter: [ '<!--', '-->' ]
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string', tagname: 'h1' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    editor:
      preview: true
